#!/usr/bin/env python3
"""
Run MedQA MPIB-style V1 patient-channel attacks in batches with resume.

This runner mirrors the existing OpenPI batch runner pattern:
- selects a batch of scenario ids
- runs one clean baseline per scenario
- runs all matching MPIB-V1 attack scripts for those scenarios
- skips completed runs when dialogue_history.json is already present

The attack scripts are generated by:
  MedAgentSim/scripts/generate_medqa_mpib_v1_dataset.py
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


VALID_RULES = ("R1", "R2", "R3", "R4", "R5", "R6")
VALID_TIMINGS = ("early", "late")
VALID_TIERS = ("strict", "realistic")
VALID_SCENARIO_FAMILIES = ("S1", "S2", "S3", "S4")


def _repo_paths() -> tuple[Path, Path]:
    script = Path(__file__).resolve()
    medsim_root = script.parents[1]
    workspace_root = medsim_root.parent
    return medsim_root, workspace_root


def parse_csv(raw: str, valid: tuple[str, ...] | None = None) -> list[str]:
    items = [item.strip() for item in raw.split(",") if item.strip()]
    if valid is not None:
        invalid = [item for item in items if item not in valid]
        if invalid:
            raise ValueError(f"Invalid values: {invalid}; allowed: {valid}")
    return items


def load_manifest_rows(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if not isinstance(row, dict):
                continue
            rows.append(row)
    return rows


def is_run_complete(output_subdir: Path, min_bytes: int = 80) -> bool:
    if not output_subdir.is_dir():
        return False
    for path in output_subdir.glob("scenario_*/dialogue_history.json"):
        try:
            if path.stat().st_size >= min_bytes:
                return True
        except OSError:
            continue
    return False


def run_subprocess(argv: list[str], cwd: Path, env: dict[str, str] | None = None) -> int:
    print("+", " ".join(argv), flush=True)
    result = subprocess.run(argv, cwd=str(cwd), env=env)
    return int(result.returncode)


def filter_manifest_rows(
    rows: list[dict],
    *,
    rules: list[str],
    timings: list[str],
    tiers: list[str],
    scenario_families: list[str],
    scenarios: set[int] | None,
) -> list[dict]:
    filtered: list[dict] = []
    for row in rows:
        try:
            scenario_id = int(row["scenario_id"])
        except (KeyError, TypeError, ValueError):
            continue
        if scenarios is not None and scenario_id not in scenarios:
            continue
        if rules and row.get("rule_family_id") not in rules:
            continue
        if timings and row.get("timing") not in timings:
            continue
        if tiers and row.get("tier") not in tiers:
            continue
        if scenario_families and row.get("scenario_family") not in scenario_families:
            continue
        filtered.append(row)
    return filtered


def select_batch_scenarios(rows: list[dict], batch_index: int, batch_size: int) -> list[int]:
    scenario_ids = sorted({int(row["scenario_id"]) for row in rows})
    start = batch_index * batch_size
    batch_ids = scenario_ids[start : start + batch_size]
    return batch_ids


def baseline_script_path(baseline_root: Path, scenario_id: int) -> Path:
    return baseline_root / f"medqa_s{scenario_id}_baseline.json"


def attack_script_path(script_root: Path, row: dict) -> Path:
    runtime = row.get("runtime") or {}
    script_file = runtime.get("script_file")
    if not isinstance(script_file, str) or not script_file.strip():
        raise ValueError(f"Manifest row is missing runtime.script_file: {row.get('sample_id')}")
    return script_root / Path(script_file)


def output_dir_for_attack(output_root: Path, row: dict) -> Path:
    runtime = row.get("runtime") or {}
    out_name = runtime.get("output_dir_name")
    if not isinstance(out_name, str) or not out_name.strip():
        sample_id = str(row.get("sample_id", "unknown"))
        out_name = sample_id
    return output_root / out_name


def main() -> int:
    medsim_root, _workspace_root = _repo_paths()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default=str(medsim_root / "scripted_inputs_medqa_mpib" / "medqa_mpib_v1_manifest.jsonl"),
        help="MPIB-V1 manifest JSONL generated by generate_medqa_mpib_v1_dataset.py",
    )
    parser.add_argument(
        "--script-input-dir",
        default=str(medsim_root / "scripted_inputs_medqa_mpib"),
        help="Root directory that contains patient/*.json MPIB-V1 attack scripts.",
    )
    parser.add_argument(
        "--baseline-script-dir",
        default=str(medsim_root / "scripted_inputs_medqa"),
        help="Directory containing medqa_s<id>_baseline.json scripts.",
    )
    parser.add_argument(
        "--output-root",
        default=str(medsim_root / "output_eval_medqa_mpib_v1"),
        help="Benchmark output root.",
    )
    parser.add_argument("--batch-index", type=int, default=0, help="0-based scenario batch index.")
    parser.add_argument("--batch-size", type=int, default=5, help="Scenarios per batch.")
    parser.add_argument(
        "--rules",
        default="",
        help="Optional subset of rule ids, e.g. R1,R2,R4,R6",
    )
    parser.add_argument(
        "--timings",
        default="",
        help="Optional subset of timings: early,late",
    )
    parser.add_argument(
        "--tiers",
        default="",
        help="Optional subset of tiers: strict,realistic",
    )
    parser.add_argument(
        "--scenario-families",
        default="",
        help="Optional subset of scenario families: S1,S2,S3,S4",
    )
    parser.add_argument(
        "--scenarios",
        default="",
        help="Optional explicit subset of scenario ids, comma-separated.",
    )
    parser.add_argument("--total-inferences", type=int, default=10)
    parser.add_argument("--doctor-llm", default=os.environ.get("DOCTOR_LLM", os.environ.get("REMOTE_LLM_MODEL", "Qwen3.5-27B-Q4_K_M.gguf")))
    parser.add_argument("--measurement-llm", default=os.environ.get("MEASUREMENT_LLM", ""))
    parser.add_argument("--moderator-llm", default=os.environ.get("MODERATOR_LLM", ""))
    parser.add_argument(
        "--doctor-image-request",
        default=os.environ.get("DOCTOR_IMAGE_REQUEST", "False"),
        help="True/False passed to medsim/main.py",
    )
    parser.add_argument(
        "--prompt-injection-defense",
        default=os.environ.get("PROMPT_INJECTION_DEFENSE", "none"),
        help="Defense mode passed to medsim/main.py",
    )
    parser.add_argument(
        "--skip-existing",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Skip runs if dialogue_history.json already exists.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print planned runs only.")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).resolve()
    script_root = Path(args.script_input_dir).resolve()
    baseline_root = Path(args.baseline_script_dir).resolve()
    output_root = Path(args.output_root).resolve()

    if not manifest_path.is_file():
        print(f"Missing manifest: {manifest_path}", file=sys.stderr)
        return 2

    main_py = medsim_root / "medsim" / "main.py"
    if not main_py.is_file():
        print(f"Missing {main_py}", file=sys.stderr)
        return 2

    rows = load_manifest_rows(manifest_path)
    rules = parse_csv(args.rules, VALID_RULES) if args.rules.strip() else []
    timings = parse_csv(args.timings, VALID_TIMINGS) if args.timings.strip() else []
    tiers = parse_csv(args.tiers, VALID_TIERS) if args.tiers.strip() else []
    scenario_families = (
        parse_csv(args.scenario_families, VALID_SCENARIO_FAMILIES)
        if args.scenario_families.strip()
        else []
    )
    explicit_scenarios = (
        {int(item) for item in parse_csv(args.scenarios)}
        if args.scenarios.strip()
        else None
    )

    filtered_rows = filter_manifest_rows(
        rows,
        rules=rules,
        timings=timings,
        tiers=tiers,
        scenario_families=scenario_families,
        scenarios=explicit_scenarios,
    )
    if not filtered_rows:
        print(
            json.dumps(
                {
                    "error": "empty_selection",
                    "manifest": str(manifest_path),
                    "rules": rules,
                    "timings": timings,
                    "tiers": tiers,
                    "scenario_families": scenario_families,
                    "scenarios": sorted(explicit_scenarios) if explicit_scenarios is not None else [],
                },
                indent=2,
            ),
            file=sys.stderr,
        )
        return 3

    batch_ids = select_batch_scenarios(filtered_rows, args.batch_index, args.batch_size)
    if not batch_ids:
        print(
            json.dumps(
                {
                    "error": "empty_batch",
                    "batch_index": args.batch_index,
                    "batch_size": args.batch_size,
                    "num_selected_scenarios": len(sorted({int(row["scenario_id"]) for row in filtered_rows})),
                },
                indent=2,
            ),
            file=sys.stderr,
        )
        return 3

    selected_rows = [row for row in filtered_rows if int(row["scenario_id"]) in set(batch_ids)]
    output_root.mkdir(parents=True, exist_ok=True)

    measurement = args.measurement_llm.strip() or args.doctor_llm
    moderator = args.moderator_llm.strip() or args.doctor_llm
    env = os.environ.copy()

    plan: list[tuple[str, int, Path, Path]] = []
    for scenario_id in batch_ids:
        base_script = baseline_script_path(baseline_root, scenario_id)
        base_output = output_root / f"s{scenario_id}_baseline"
        plan.append((f"{scenario_id}/baseline", scenario_id, base_script, base_output))

    for row in selected_rows:
        scenario_id = int(row["scenario_id"])
        script_path = attack_script_path(script_root, row)
        attack_output = output_dir_for_attack(output_root, row)
        label = str(row.get("sample_id") or f"{scenario_id}/attack")
        plan.append((label, scenario_id, script_path, attack_output))

    for label, scenario_id, script_path, out_dir in plan:
        if not script_path.is_file():
            print(f"Missing script: {script_path}", file=sys.stderr)
            return 4
        if args.skip_existing and is_run_complete(out_dir):
            print(f"skip (done): {out_dir}", flush=True)
            continue
        if args.dry_run:
            print(f"[dry-run] would run scenario {label} -> {out_dir}")
            continue

        argv = [
            sys.executable,
            str(main_py),
            "--inf_type",
            "human_patient",
            "--agent_dataset",
            "MedQA",
            "--num_scenarios",
            "1",
            "--start_scenario",
            str(scenario_id),
            "--total_inferences",
            str(args.total_inferences),
            "--doctor_llm",
            args.doctor_llm,
            "--measurement_llm",
            measurement,
            "--moderator_llm",
            moderator,
            "--doctor_image_request",
            args.doctor_image_request,
            "--prompt_injection_defense",
            args.prompt_injection_defense,
            "--human_patient_script",
            str(script_path),
            "--output_dir",
            str(out_dir),
        ]
        rc = run_subprocess(argv, cwd=medsim_root, env=env)
        if rc != 0:
            print(f"Run failed (exit {rc}) for {label}", file=sys.stderr)
            return rc

    print(
        json.dumps(
            {
                "completed_batch": True,
                "surface": "patient",
                "dataset": "MedQA",
                "attack_dataset": "MPIB-MedAgentSim-V1",
                "scenarios": batch_ids,
                "num_attack_runs": len(selected_rows),
                "output_root": str(output_root),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
